services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    command: npm run watch
    develop:
      watch:
        - action: sync
          path: ./backend/src
          target: /src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./backend/src
    ports:
      - "3001:3001"
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
      - "8080:8080"
      - "4200:4200"

